### PR TITLE
F/initial import

### PR DESCRIPTION
**Pull request by beporter**
Imports a Cake 3 version of the shell from another project.

### CODE REVIEW

**Comment by beporter** [comment]
TODO:
- [x] Figure out the conditions under which using both the plugin name and the shell name are unnecessary when dealing with a composer-installed plugin.
  
  Ref: http://book.cakephp.org/3.0/en/console-and-shells.html#the-cakephp-console
  
  > Plugin shells can be invoked without a plugin prefix if the shell’s name does not overlap with an application or framework shell. In the case that two plugins provide a shell with the same name, the first loaded plugin will get the short alias. You can always use the plugin.shell format to unambiguously reference a shell.
  
  Make sure we name our composer package to be compatible with this usage. (Or is this tied to the plugin's namespace??)
- [x] Add .travis.yml
- [x] Enable Travis builds
- [x] Enable Coveralls
- [x] Submit to packagist
- [x] Tag a `1.0.0` release
- [x] Create a `cake-2.x` branch
  - [x] Import existing 2.x codebase from FM-Server.

**Comment by beporter** [comment]
There's still a logic error when trying to `INSERT` seed records with a fixed ID value. Need to look at how Cake's test fixtures manage that. Assigning back to me.

**Comment by josegonzalez** [comment]
Your shell name is called `uuid`. As long as the framework doesn't provide such a shell in it's core, _and_ that a user doesn't add their own UuidShell to their app, you should be fine. Note that if you have two such shells under different namespaces, you'll need to specify a plugin prefix to disambiguate them.

**Comment by beporter** [comment]
Thanks, that's clear now. I just haven't had time to come back around and get this finalized. I could spend a few months just doing all the open source work I have queued up. I don't know how you core team folks do it. Props to all of you though.

**Comment by beporter** [comment]
Created #2 to track the Cake 2 version separately.

**Pull request merged**
